### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by alexwennerberg** [admacleod/gmi2html#1]
Hi! I wrote a fork of this library with a few changes:
- html safety
- url scheme safety
- fixed a bug with unclosed blocks/lists
- added tests
- converted from CLI tool to a library

I found all the other Go libraries that did this were either too complex (used parsers/lexers/regex) and so I used this one as a starting point. This is just for my own personal use, but wanted to let you know in case you were interested!

https://git.sr.ht/~aw/gmi2html

**Comment by admacleod** [comment]
That's awesome! Glad you were able to make good use of it as a starting point.

I probably should mark this as archived because I'm unlikely to do any further work on it but I'll take a look at your work and probably put something in the readme to point people your way if they're looking for something similar, if you would like?

**Comment by alexwennerberg** [comment]
sure that would be cool! alexalexw.nycOn Aug 4, 2024, at 3:56 AM, Alisdair MacLeod ***@***.***> wrote:﻿
That's awesome! Glad you were able to make good use of it as a starting point.
I probably should mark this as archived because I'm unlikely to do any further work on it but I'll take a look at your work and probably put something in the readme to point people your way if they're looking for something similar, if you would like?

**Comment by admacleod** [comment]
Done! Keep up the great work!
